/* This file is auto-generated by amiibo_db_gen.py. Do not edit directly. */
#include "db_header.h"
const db_game_t game_list[] = {
{11, 0, "Animal Crossing: New Horizons", "集合啦！动物森友会", 99, 525}, 
{52, 11, "Amiibo Cards", "Amiibo Cards", 0, 509}, 
{53, 11, "Amiibo Figures", "Amiibo Figures", 0, 16}, 
{54, 52, "Amiibo Festival", "Amiibo Festival", 0, 3}, 
{55, 52, "Sanrio Cards", "Sanrio Cards", 0, 6}, 
{56, 52, "Series 1", "Series 1", 0, 100}, 
{57, 52, "Series 2", "Series 2", 0, 100}, 
{58, 52, "Series 3", "Series 3", 0, 100}, 
{59, 52, "Series 4", "Series 4", 0, 100}, 
{60, 52, "Series 5", "Series 5", 0, 48}, 
{61, 52, "Special Edition", "Special Edition", 0, 2}, 
{62, 52, "Welcome Amiibo", "Welcome Amiibo", 0, 50}, 
{0, 0, 0, 0, 0}
};
